##############################################################################
# Copyright (c) 2019-2021, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

stages:
  - concretize-alone
  - concretize-group
  - concretize-all

# Defines the rules to run spack-environment CI
.concretize_rules:
  rules:
    - changes:
      - spack-environments/**/*
    - if: '$CONCRETIZATION_TESTING'
    - if: '$TRIGGER_SPACK_PIPELINES'

.concretize:
  extends: .concretize_rules
  tags:
    - shell
    - lassen   # - quartz
  before_script:
    - date
    - git clone ${CHILD_SPACK_PATH} --depth 1 local_spack
    - . local_spack/share/spack/setup-env.sh
    - cd spack-environments/empty
    - spack ${CHILD_SPACK_DEBUG} env activate .
    - cd -
  after_script:
    - date

.concretize_command: &concretize_command |
  spack ${CHILD_SPACK_DEBUG} concretize

.concretize-alone:
  extends: .concretize
  stage: concretize-alone

.concretize-group:
  extends: .concretize
  stage: concretize-group

.concretize-all:
  extends: .concretize
  stage: concretize-all

concretize_umpire:
  extends: .concretize-alone
  script:
    - spack add umpire
    - *concretize_command

concretize_raja:
  extends: .concretize-alone
  script:
    - spack add raja
    - *concretize_command

concretize_hypre:
  extends: .concretize-alone
  script:
    - spack add hypre
    - *concretize_command

concretize_mfem:
  extends: .concretize-alone
  script:
    - spack add mfem
    - *concretize_command

concretize_conduit:
  extends: .concretize-alone
  script:
    - spack add conduit
    - *concretize_command

concretize_sundials:
  extends: .concretize-alone
  script:
    - spack add sundials
    - *concretize_command

concretize_samrai:
  extends: .concretize-alone
  script:
    - spack add samrai
    - *concretize_command

concretize_xbraid:
  extends: .concretize-alone
  script:
    - spack add xbraid
    - *concretize_command

concretize_ascent:
  extends: .concretize-alone
  script:
    - spack add ascent
    - *concretize_command

concretize_zfp:
  extends: .concretize-alone
  script:
    - spack add zfp
    - *concretize_command

concretize_scr:
  extends: .concretize-alone
  script:
    - spack add scr
    - *concretize_command

concretize_visit:
  extends: .concretize-alone
  script:
    - spack add visit
    - *concretize_command

concretize_glvis:
  extends: .concretize-alone
  script:
    - spack add glvis
    - *concretize_command

concretize_caliper:
  extends: .concretize-alone
  script:
    - spack add caliper
    - *concretize_command

concretize_spindle:
  extends: .concretize-alone
  script:
    - spack add spindle
    - *concretize_command

concretize_flux-sched:
  extends: .concretize-alone
  script:
    - spack add flux-sched
    - *concretize_command

concretize_py-maestrowf:
  extends: .concretize-alone
  script:
    - spack add py-maestrowf
    - *concretize_command

concretize_math_physics:
  extends: .concretize-group
  script:
    - spack add mfem hypre sundials samrai xbraid
    - *concretize_command
  needs: [concretize_mfem, concretize_hypre, concretize_sundials, concretize_samrai, concretize_xbraid]

concretize_data_visualization:
  extends: .concretize-group
  script:
    - spack add conduit ascent zfp scr visit
    - *concretize_command
  needs: [concretize_conduit, concretize_ascent, concretize_zfp, concretize_scr, concretize_visit]

concretize_portability_memory:
  extends: .concretize-group
  script:
    - spack add umpire raja
    - *concretize_command
  needs: [concretize_umpire, concretize_raja]

concretize_performances_workflow:
  extends: .concretize-group
  script:
    - spack add caliper spindle flux-sched py-maestrowf
    - *concretize_command
  needs: [concretize_caliper, concretize_spindle, concretize_flux-sched, concretize_py-maestrowf]

concretize_radiuss:
  extends: .concretize-all
  script:
    - spack add caliper spindle flux-sched py-maestrowf mfem hypre sundials samrai xbraid conduit ascent zfp scr visit umpire raja
    - *concretize_command
  needs: [concretize_math_physics, concretize_data_visualization, concretize_portability_memory, concretize_performances_workflow]
  artifacts:
    paths:
      - spack-environments/empty
