#!/bin/bash

set -e

# Check necessary variables
spack_ref=${SPACK_REF:-""}
spack_repo=${SPACK_REPO:-""}

usage() {
  echo " $0 needs either a branch or a hash."
  echo " Use \$SPACK_REF to specify it."
  echo ""
  echo " $0 needs a repository url."
  echo " Use \$SPACK_REPO to specify it."
}

if [[ -z ${spack_ref} ]]; then
  echo "[ERROR] No branch or hash are defined in \$SPACK_REF."
  usage
fi

if [[ -z ${spack_repo} ]]; then
  echo "[ERROR] No repository defined in \$SPACK_REPO."
  usage
fi

#[get-spack--]
# Create a new repo if not present, and prepare for fetch
if [[ ! -d ${SPACK_PATH} ]]
then
  mkdir -p ${SPACK_PATH}
  cd ${SPACK_PATH}
  git init
  git remote add origin ${spack_repo}
fi

# Go to the repo.
cd ${SPACK_PATH}

# Fetch the reference.
git fetch --depth 1 origin ${spack_ref}

# Checkout the reference.
git checkout FETCH_HEAD

# Tag the commit with current pipeline ID.
git tag ${CI_PIPELINE_ID}
#[--get-spack]
