#!/bin/bash

if [[ ! -d ${SPACK_PATH} ]]
then
  cd ${SPACK_PATH}
  git apply ${CI_PROJECT_DIR}/patches/spack/user-scope.patch
  git commit -am "Moving user scope in spack directory"
  cd -
else
  echo "\$SPACK_PATH = $SPACK_PATH is not a directory,"
  echo "be sure to run get-spack first."
  exit 1
fi
