#!/bin/bash

vars="PROJECT_NAME SPACK_REF SPACK_REPO SPACK_PATH"

echo "--------------------------------"
echo "---- Variables of interest "
echo "--------------------------------"

for var in ${vars};
do
  echo "---- ${var} = ${!var} "
done

echo "--------------------------------"
